name: Controlling the Execution Flow

on:
    workflow_dispatch:
      inputs:
        pass-unit-tests:
          type: boolean
          description: Whether unit tests will pass or not
          default: true

jobs:
    lint-build:
      runs-on: ubuntu-latest
      steps:
        - name: Lint and build
          run: echo "Linting and building project"
    unit-test:
      runs-on: ubuntu-latest
      continue-on-error: true
      steps:
        - name: Running unit tests
          run: echo "Running tests..."
        - name: Failing tests
          if: ${{ !inputs.pass-unit-tests }}
          run: exit 1
    deploy-nonprod:
      runs-on: ubuntu-latest
      needs:
        - lint-build
        - unit-test
      steps:
        - name: Deploying to non-prod
          run: echo "Deploying to non-prod"
    e2e-test:
      runs-on: ubuntu-latest
      needs:
        - deploy-nonprod
      steps:
        - name: Running e2e tests
          run: echo "Running e2e tests"
    loads-test:
      runs-on: ubuntu-latest
      needs:
        - deploy-nonprod
      steps:
        - name: Running loads tests
          run: echo "Running loads tests"
    deploy-prod:
      runs-on: ubuntu-latest
      needs:
        - e2e-test
        - loads-test
      steps:
        - name: Deploying to prod
          run: echo "Deploying to prod"
        
